### ISSUE TITLE
Update for new anthropic version please

### ISSUE THREAD

**Issue by BedirT** [MagnivOrg/prompt-layer-library#152] opened 2024-06-20 22:55 UTC
https://github.com/anthropics/anthropic-sdk-python/releases/tag/v0.29.0 for the new claude model

**Comment by abubakarsohail** [comment] 2024-06-21 07:03
> https://github.com/anthropics/anthropic-sdk-python/releases/tag/v0.29.0 for the new claude model

Hi @BedirT the library should work with the latest version of anthropic SDK. Can you tell us a little bit more about the issue you are facing?

**Comment by abubakarsohail** [comment] 2024-06-24 10:12
Closing this as the SDK already supports this

**Comment by abubakarsohail** [comment] 2024-06-24 10:22
I see what the issue is. `anthropic` and `openai` are added as a dependency, which is wrong. Will fix this with a PR soon.

**Closed** 2024-06-24 10:33 UTC
